#!/bin/bash
if git diff --cached|grep 'fbd(\|deb(|debug(' > /dev/null
then 
	echo "Commit contains debug"
	exit 1
fi

for file in `git diff --cached --diff-filter=ACMRTUXB --name-only HEAD`
do              
  if [[ "$file" == *.php ]] || [[ "$file" == *.phtml ]] && ! phpcs --standard=TOL $file
  then
    echo $file
    invalid=true;
  else
    if [[ "$file" == *.js ]] && ! phpcs --standard=TOL $file
    then
      echo $file
      invalid=true;
    fi
    if [[ "$file" == *.js ]] && ! python `git rev-parse --git-dir`/hooks/gjslint.py --jslint_error all $file
    then
      echo $file
      invalid=true;
    fi
  fi    
done            
                
if [ "$invalid" = "true" ]
then
  exit 1;
fi

git diff --cached --name-status | while read st file; do
        # skip deleted files
        if [ "$st" == 'D' ]
	then 
		continue
	fi
        # do a check only on the php files
        if [[ "$file" == *.php ]] || [[ "$file" == *.phtml ]] && ! php -l "$file"
	then
                echo "PHP syntax check failed for file: $file"
                exit 1
        fi
done
